>P1;sp|P02186|MYG_ELEMA/1-154
Myoglobin OS=Elephas maximus GN=MB PE=1 SV=3
MGLSDGEWELVLKTWGKVEADIPGHGETVFVRLFTGHPETLEKFDKFKHLKTEGEMKASEDLKKQGVTVLTA
LGGILKKKGHHEAEIQPLAQSHATKHKIPIKYLEFISDAIIHVLQSKHPAEFGADAQGAMKKALELFRNDIA
AKYKELGFQG---*
>P1;sp|P03298|ICP18_FRG3G/1-157
Immediate-early protein ICP-18 OS=Frog virus 3 (isolate Goorha) GN=FV3-082R PE=4 SV=1
MRMIQAYLCDSVSGEPYTCKGDLCEIPFNRNFTIDLVNLSVSTEFQVKITMTPHHDLGTFVVEPKNVFSIKR
AVKGDAAFKVERAAGWLPDTPQVLTLFVYERLNPVEWHSECMYENLETDGGTVIVPGEATGQRFGTATEVPT
MFLFKRMFVVKGV*
